/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laboratorio2;

/**
 *
 * @author lrpor
 */
public class ventanaReinicioClave extends javax.swing.JFrame {

    /**
     * Creates new form ventanaReinicioClave
     */
    public ventanaReinicioClave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConfirmarClave = new javax.swing.JPasswordField();
        txtNuevaClave = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nueva clave:");

        jLabel2.setText("Confirmar clave:");

        txtConfirmarClave.setText("jPasswordField1");

        txtNuevaClave.setText("jPasswordField2");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(txtConfirmarClave)
                    .addComponent(txtNuevaClave))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNuevaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConfirmarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // 1. Obtenemos lo que el usuario escribió (JPasswordField requiere este formato especial)
        String nueva = new String(txtNuevaClave.getPassword());
        String confirmar = new String(txtConfirmarClave.getPassword());

        // Validación 1: ¿Están vacíos?
        if (nueva.isEmpty() || confirmar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena ambos campos.", "Alerta", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución
        }

        // Validación 2: ¿Coinciden las dos contraseñas?
        if (!nueva.equals(confirmar)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. Revisa e intenta de nuevo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación 3: ¿Tiene al menos 13 caracteres?
        if (nueva.length() < 13) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tu nueva clave debe tener al menos 13 caracteres por seguridad.", "Seguridad débil", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación 4: ¿Tiene al menos una letra mayúscula?
        // Usamos "matches" para buscar de la A a la Z en mayúsculas en cualquier parte del texto
        if (!nueva.matches(".*[A-Z].*")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Falta una letra mayúscula en tu contraseña.", "Seguridad débil", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación 5: ¿Tiene al menos un signo especial?
        // Esto busca cualquier símbolo que no sea una letra ni un número
        if (!nueva.matches(".*[^a-zA-Z0-9].*")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes incluir al menos un signo especial (ej. @, #, $, %, -, *, etc.).", "Seguridad débil", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si el código llega hasta aquí, significa que sobrevivió a todos los filtros
        javax.swing.JOptionPane.showMessageDialog(this, "¡Contraseña actualizada con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Limpiamos las cajas para que queden en blanco
        txtNuevaClave.setText("");
        txtConfirmarClave.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        ventanaMenuPrincipal menu = new ventanaMenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaReinicioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaReinicioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaReinicioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaReinicioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaReinicioClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtConfirmarClave;
    private javax.swing.JPasswordField txtNuevaClave;
    // End of variables declaration//GEN-END:variables
}
